#pragma once

#define IOCTL_VIRTUALIZE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1336, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_DEVIRTUALIZE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1337, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)